### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by ghost** [undecidables/COSBAS-Client#7]

**Comment by Babalela01** [comment]
The controllers already use depenfency injection

**Comment by Babalela01** [comment]
Oh no nvm, I see this is the client :P

**Comment by VivianLVenter** [comment]
Renette can we close this?

**Comment by Mistborn94** [comment]
Talk to szymon

**Comment by VivianLVenter** [comment]
Oh I just seen its on the Client...

Szymon?

**Comment by ghost** [comment]
Already closed, sorry for the late response
