### ISSUE TITLE
Open CV on repo?

### ISSUE THREAD

**Issue by Mistborn94** [undecidables/COSBAS-Client#9]
An openCV jar was stored on the repo, why? It should be downloaded using gradle if I am not mistaken...

I removed it but if it is really necessary we can put it back

**Comment by Mistborn94** [comment]
Build at commit b485fc046cfe7598115b58228d2fdf5a153d730e requires it, but ideally it should be reworked into a downloaded gradle dependency.

**Comment by ghost** [comment]
I will give it another go and see what i can do.

**Comment by thepickpocket** [comment]
@masterfloki can we close this??

**Comment by ghost** [comment]
yeah uhm i couldn't get opencv to work off gradle. so would have to manually install it on client pc.
